# Generated by Django 2.0.2 on 2018-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_accept_agreement',
            field=models.BooleanField(default=True),
        ),
    ]
