language: python
python:
  - '3.6'

env:
  - DJANGO_SETTINGS_MODULE='_game_chats.settings.test_settings'

addons:
  - postgresql: "10"

branches:
  only:
  - master

install:
- pip install -r requirements/base.txt
- pip install coveralls

before_script:
  - psql -c "CREATE DATABASE gamechats_db;" -U postgres

script:
  - python manage.py migrate --noinput
  - pytest
after_success: coveralls

deploy:
  provider: heroku
  app: testgamechats
  api_key:
    secure: tz1GFfj1RE/79rO6syfPzJqvBbp9vFtfkYo4YXDP+TtUBu6YqjYYs82M02NrpRObIRhUZL+YTrQfOo0lSpg/t+C2DBwcvNovXPgLku9KysCKRUZF2CgdEFXR9axwQShDU8hOP2Up34J6KcX5agFpPxQTnTtrK5f5I4lQQbShErIkgxM9AxE518HbSijK5RsyIKHvdFINgOLA4t9AeRqGRJ+FxoQUJJSH6W3mV12ieXrK9qL4tpvpjiLTWr6tTLYAkfbbcAjPwSCfDgoYU6erj+VZmwmiZ0sQeFkuMFjkKVvmRJsZUbulxGDlQjyItgZ+WDmvevsJimVbyS0WGFTQMPKDb6xTNi8KC1S/yLQmVvbdgHIKqxpWHJPsVJ3CqQ7afgMtmFOnmUeThMmigrUHFZnzeyecz19Bs5RDHovHoxasRukm7weeNpXWzCnuobyUosk4JE2ycXGXvYdSVIBNF6vMpngQwzR23w91jsDVptXAJivNfiMBvNKhGvx35DNsKJLs41qpOxJBS2QMItlXgQ3uID/6dIcVnAuM2Ayjg5qM/0P4KOonJUjBnbOu5HgCGAGwp+BhCEM2/mOsw3VGfFQACsm/Sfavx2pR/3LRjYTqwvxV3R7vKoeqX19h2ZAKRE35p5HZueZYKb0oo/ISUQptIMKg3vAu2P+UcCRoKKw=

notifications:
  slack: gamechats:pjaTb9uiTnnpJHgjQ9pJ7vFc
  on_success: always
  on_failure: always
