language: python
python:
- '3.6'
env:
  matrix:
  - DJANGO_SETTINGS_MODULE='_game_chats.settings.base'
addons:
- postgresql: '10'
branches:
  only:
  - master
install:
- pip install -r requirements/base.txt
- npm install
- pip install coveralls
before_script:
- psql -c "CREATE DATABASE gamechats_db;" -U postgres
- node_modules/.bin/webpack --config webpack.config.js
script:
- python manage.py migrate --noinput
- pytest
after_success: coveralls
notifications:
  slack: gamechats:pjaTb9uiTnnpJHgjQ9pJ7vFc
  on_success: change
  on_failure: always
