language: python
python:
- '3.6'
env:
  matrix:
  - DJANGO_SETTINGS_MODULE='_game_chats.settings.base'
  global:
  - secure: b17qAElaRbMMbNbOGWHGg/BR1o/7jo7NGUUdiVGF5fN/wzcX06GI8gSYQwG7ib05kEp6R1+MtBBcSw2VzcSyXrRS7rP1zuECZcxdJ/XCyijQJLHOoJP4AcVpyde21Y0ME8d3SM17px1QrTBhf7C01Xg3XI7RTLwyz2HhzwsgCACPhHUuqB01G1YCP+AtcBrYOJIgh+ilbB5FgnqX2I8V7SQ5KMoTtQ4WM6/E/x44KEruW8MZ+iHqMPkmPwY7XwNxepJxbWzERsvkwn8fhPQxqO2dyxBdCerq5k/Jnh6ieHX0U8tIl4BGOmjHu8A6EPQFydjLJ/O8gxNH/5grsy43YQtTCVxmw566XPN/o3wUa9qkHP66w0lAMZnuvbrfPGQ3TzFAlnvt4wuJ7bzoj5axPxibQUARfy3uPoV7HzQ0JEObAmsDX/TV5IVNfC34NDZa1M7LtWm7K56aJ6cZFD/kRH6CaH3ci4JPPIq1x3EAEovaKPnn1Ga6R4OPuNLrVD+CeSHjOpvlHbbGj63gxN6lbwbBxrRSDNwGLpgL9JhZ0QNlMLh8Ndp/Wgtejp30+9JgT9dN3x8Fl0o/mPZmU95WoV5Hy47N2qkJWfP0bqnReVivNY1EAAwl07ldNAZuNEwc1mrFuaPPs7yYZLdkkQ13RaKIxfBLjvbkxdKyhKlOwpg=
  - secure: NFLzaiCds9Cumcz8n180a9ntJSueUdJUVt1zrb3daYjvth64TegHuvYNAvO7MlnWw7p4vbPcEdnwS1yCS+r8H+jUz+TIDlYfRDy9mq1uY8UB6LgsahUIkUvKs1JbAxYyTbifXMYTTT1FlmW261caeAawTVx5DwBfINxCLDOjo+8aBxJv6stwfayNbnjprpAFMmUSdKR9s5DlwkqRp1aS+8i8ZQQD2JvF5pMAPwIWxP3sGzbK5mEz3DU9QoOHi3jl78le1doUhCOxNryity1hPXkk+nLXJKHEXGxsFhR5mTzr+mjyOroSdSdDK4jaCauVGVYff/OPw6Eld/eQisij/4j0CA43dKcZ2dvEjT/kE4P+SQC7EqR5X8VUXFWEkxQuaEHhekLSfvZMH0bdoaD9rCFRxX92paByec0qW1FVKHxufkk+KHxTwlwkujX9eYjj2bZwZjIAM/6p+Bz7uS9EhmrIrcjCA1+NhDLAFno7nF1KYQyP0CpHOAhMkU1ZKjclkdvWi+J7QtGyUpvk/LgeWoP3lEPXIqeuRbc4iB1a34equfnHruduH1Q7WvO8dONShuJN6ByViABUci3qDwDYolOwuS3+B8FsBe4Wf41EjMJKzP8FAeDgZ1vkYacOYfvjGCJib0R7a5QclTRIjekLBXcWpqaBK3R+NllXjNA3Q/Q=
addons:
- postgresql: '10'
branches:
  only:
  - master
install:
- pip install -r requirements/base.txt
- npm install
- pip install coveralls
before_script:
- psql -c "CREATE DATABASE gamechats_db;" -U postgres
- node_modules/.bin/webpack --config webpack.config.js
script:
- python manage.py migrate --noinput
- pytest --ds=_game_chats.settings.staging
after_success: coveralls
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: $aws_access_key_id
  secret_access_key:
    secure: $aws_secret_access_key
  region: us-east-1
  app: gamechats-elasticbeanstalk
  env: gamechatsElasticbea-env
  bucket_name: elasticbeanstalk-us-east-1-711704628243
notifications:
  slack: gamechats:pjaTb9uiTnnpJHgjQ9pJ7vFc
  on_success: change
  on_failure: always
