language: python
python:
  - "3.6"
install:
  - pip install -r requirements/base.txt
  - pip install coveralls
script:
  - pytest
after_success: coveralls
notifications:
    slack: gamechats:pjaTb9uiTnnpJHgjQ9pJ7vFc
    on_success: always
    on_failure: always
  