version: '3'

services:
  app:
    image: nodejs_app
    restart: always
    build: .
    command: node /var/www/_game_chats/server.js
    ports:
      - "3000:3000"
  db:
    image: postgres:10.1
    volumes:
      - postgres_data:/var/lib/postgresl/data/
  redis:
    image: redis
    ports:
      - '6379:6379'
  celery:
    build: .
    env_file: .env
    command: celery -A _game_chats worker -l info -Q user_tasks_queue
    volumes:
      - .:/var/www/_game_chats
    links:
      - redis
    depends_on:
      - redis
  web:
    build: .
    command: python3 manage.py migrate --settings=_game_chats.settings.staging
    command: python3 manage.py runserver 0.0.0.0:8001  --settings=_game_chats.settings.staging
    volumes:
      - .:/var/www/_game_chats
    ports:
      - "8001:8001"
    depends_on:
      - db
      - redis
      - celery

volumes:
  postgres_data: